# SPDX-FileCopyrightText: Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

name: "Benchmarks"
permissions: read-all

on:
  workflow_dispatch:
  # 6am UTC is 10pm PST, 11pm PDT
  schedule:
    - cron: '0 6 * * *'
    
env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  gbench:
    runs-on: pvc
    name: "JFCST Benchmarks"
    env:
      CXX: icpx
      FI_PROVIDER: tcp
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install python dependencies
        run: pip install src-python/drbench/drbench
      - name: Generate
        run: cmake -B build
      - name: Build
        run: cmake --build build --target xhp-bench -- -j
      - name: Run
        run: |
          source /opt/intel/oneapi/2024.0.1/setvars.sh
          srun --nodes=4 --ntasks-per-node=2 make -C build/benchmarks/gbench jfcst-bench-results
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: benchmarks
          path: |
            build/benchmarks
