# SPDX-FileCopyrightText: Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

name: Daily

on:
  workflow_dispatch:
  # 8am UTC is 12am PST, 1am PDT
  schedule:
    - cron: '0 8 * * *'

jobs:
  devcloud:
    runs-on: devcloud
    name: "Devcloud Benchmarking"
    env:
      CXX: icpx
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
    - uses: actions/checkout@v3
    - name: Python setup
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'
    - name: Install python packages
      run: pip install -r requirements.txt
    - name: Install benchmark framework
      run: pip install src-python/drbench
    - name: Build
      run: srun -p pvc-shared scripts/devcloud-build.sh
    - name: Benchmark
      run: srun -p pvc scripts/devcloud-benchmarks.sh
    - name: Upload benchmark results
      uses: actions/upload-artifact@v3
      with:
        name: log-devcloud-bench
        path: |
          build/benchmarks/gbench/dr-bench*.json
          build/benchmarks/gbench/*.png
    - name: Upload build logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: log-icpx
        path: build/Testing

  publish:
    needs: [devcloud]
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v3
    - name: Download benchmark results
      uses: actions/download-artifact@v3
      with:
        name: log-devcloud-bench
        path: bench/devcloud
    - name: Checkout gh-pages
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: gh-pages
    - name: Publish to github pages
      run: |
        touch gh-pages/.nojekyll
        mkdir -p gh-pages/bench

        rm -rf gh-pages/bench/devcloud
        cp -r bench/devcloud gh-pages/bench

        cd gh-pages
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        # Ignore errors because no updates returns an error status.
        git commit --reset-author --amend -m "Update from github actions"
        git push --force origin gh-pages
