# SPDX-FileCopyrightText: Intel Corporation
#
# SPDX-License-Identifier: BSD-3-Clause

name: "oneDPL"
permissions: read-all

on:
  workflow_dispatch:
  # 6am UTC is 10pm PST, 11pm PDT
  schedule:
    - cron: '0 6 * * *'

jobs:
  onedpl:
    runs-on: gkpvc
    timeout-minutes: 20
    env:
      CXX: icpx
      CTEST_OUTPUT_ON_FAILURE: 1
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
    - name: Checkout Distributed Ranges branch in oneDPL
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        repository: oneapi-src/oneDPL
        ref: distributed-ranges
        path: dr
    - name: Generate
      run: cmake -B dr/build -DCMAKE_CXX_STANDARD=23 -DCMAKE_CXX_COMPILER=icpx -DONEDPL_BACKEND=dpcpp -DCMAKE_BUILD_TYPE=Release dr
    - name: Build SHP tests
      run: cmake --build dr/build --target shp-all-tests -- -j
    - name: Run SHP tests
      run: ctest --test-dir dr/build -L SHP -j 4
    # srun -p cluster dr/scripts/run_command_on_compute_node.sh dr/build/Testing/tests.outerr.txt ctest --test-dir dr/build -L TESTLABEL -j 4
    - uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
      if: always()
      with:
        name: log-pvc-impi-icpx
        path: |
          dr/build/CMakeCache.txt
          dr/build/test/distributed-ranges/shp/*.log
